extends: default

# Rules with adjusted levels based on potential issues
rules:
  # Enforce consistent indentation (recommended)
  indentation:
    level: warning
    indent-sequences: consistent

  # Line length checks with some relaxation (adjust as needed)
  line-length:
    level: warning
    max-length: 120 # Adjust this value based on your preference

  # Allow apt-get usage in RUN instructions (depends on security context)
  # Consider using alternatives like multi-stage builds for production
  apt: enable

  # Allow environment variable assignments (might be risky depending on source)
  env: enable

# Rules likely not relevant for this specific Dockerfile
disabled_rules: empty-lines # Consider enabling for better readability

