name: Update getstarted.sh on oakestra.github.io

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ main ]
    paths:
        - 'scripts/StartOakestraFull.sh'  # Only trigger on changes to this file

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Copy-to-Another-Repository@v1
        with:

          # required parameters
          target-filepath: 'scripts/StartOakestraFull.sh'      # file path to copy
          output-branch: 'main'   # branch name to create pull request
          output-repo: 'AmazingThingsLikeCI/oakestra.github.io'
          git-token: ${{ secrets.OAKESTRA_SITE_REPO_ACCESS_TOKEN }}
          
          # optional parameters and default values
          commit-message-prefix: '[actions] '   # followed by source repository and file name
          output-directory: "${{ github.event.repository.name }}"   # copy file into sub directory
          pr-branch-prefix: "actions/${{ github.event.repository.name }}"   # branch name prefix followed by date and time
          pr-title: "GitHub Actions: ${{ github.event.repository.name }}"   # followed by source repository and file name
          pr-message: "${{ github.workflow }} on ${{ github.server_url }}/${{ github.repository }}"   # followed by action repository
          git-name: "github-actions[bot]"   # your name can be set by ${{ github.actor }}
          git-email: 'github-actions[bot]@users.noreply.github.com'   # associated user icon is shown in commit page

# {% endraw %}