on:
    push:
        # branches: [ main ]
        paths:
          - 'scripts/StartOakestraFull.sh'  # Only trigger on changes to this file
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes startup script to Oakestra site
      uses: nkoppel/push-files-to-another-repository@1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.OAKESTRA_SITE_REPO_ACCESS_TOKEN }}
      with:
        source_file: 'scripts/StartOakestraFull.sh'
        destination_repo: 'AmazingThingsLikeCI/oakestra.github.io'
        destination_folder: 'scripts'
        user_email: 'lucapinta@live.it'
        commit_message: 'Yey'
