name: Update getstarted.sh on oakestra.github.io
on:
    push:
        branches: [ main ]
        paths:
          - 'scripts/StartOakestraFull.sh'  # Only trigger on changes to this file
    
jobs:
           copy-files:
             runs-on: ubuntu-latest
             steps:
               - name: Checkout
                 uses: actions/checkout@v3
               - name: Rename files (optional)
                 run: |
                    mv scripts/StartOakestraFull.sh scripts/getstarted.sh
                    mv scripts/getstarted.sh ../
               - name: Push test folder & 1 file
                 uses: dobbelina/multi_file_bandit@main
                 env:
                   API_TOKEN_GITHUB: ${{ secrets.OAKESTRA_SITE_REPO_ACCESS_TOKEN }}
                 with:
                   source_file: "getstarted.sh"
                   destination_repo: "dobbelina/release-test"
                   destination_folder: "" # Omit if destination root
                   user_email: "lucapinta@live.it"
                   user_name: "TheDarkPyotr"
                   commit_message: ${{ github.event.head_commit.message }}
                   rsync_option: "" # Deletes any files in the 
                                                  # destination that is not
                                                  # present in the source 